### ISSUE TITLE
Populate results while entering the 1 character 

### ISSUE THREAD

**Issue by HimansuB007** [seatgeek/android-PlacesAutocompleteTextView#65]
Currently the results starts populating after the 3 character entered.  How can we populate as soon as user enters the fist character. 

setThreshold to 1 also does not work and it starts populating from the second character.

**Comment by sddamico** [comment]
@HimansuB007 I think the only way to accomplish this would be to subclass the PlacesAutocompleteTextView and always return true from the check threshold method (I'm forgetting the name of it, you'd have to read the Android source for AutocompleteTextView).

I'll just add that a threshold of 1 is generally bad practice for something like searching for a place since the set of possible results is quite large and a single character is not a strong enough signal to produce meaningful results from it.
